### PR TITLE
Responsive layout for State, Mapping, and Task Pages

### LINKED ISSUE #39: Responsive Layout of Interface
Hi, first of all, thanks a bunch for working on this. This is already so much better than the Sunray app and probably saved me from selling this mower. Also, I have python (web dev and data analysis with pandas), javascript (react), flutter, and web/app design experience. So, while I'll be submitting some issues in github, I also expect to pick up some of them to work on as I have time.

So, I'm using this application on a laptop, hooked up to a large monitor much of the time. The layout seems rather restricted and I'm curious if that is something that is limited by the map functionality, or just needs some basic css updates.

Here is what I see at the moment:
image

I noticed this is using bootstrap and with one quick change here:
image

From `col-lg-12 col-sm-6 col-12` to `col-lg-12 col-sm-6 col-12`, it at least takes up the full width. I wasn't able to quickly identify small changes to get it to be more "app-like" where the actions stick to the bottom and the main area expands to take up the space between the navbar and actions, but that is essentially what we probably should work towards.

image

### PR DESCRIPTION
**Pull request by rothnic**
This integrates my responsive updates based on master, plus applies them to the task page as well. The handling of buttons isn't the best, but this should give us a decent starting point to move forward from.

Closes #39 and replaces PR #44.

### CODE REVIEW

**Comment by rothnic** [comment]
Some screenshots of this branch. The one thing I see that isn't working as expected, but I think is consistent with master is the Task page map doesn't autosize quite the same as the others.

State Page - Large
image

State Page - Mobile
image

State Page - Mobile - Expanded Nav
image

Task Page - Large
image

Task Page - Mobile (not the biggest fan of this, but this gets us started somewhere)
image

Task Page - Mobile - Order Tasks Modal Opened
image

Mapping Page - Mobile (could use some thought about handling all these buttons a little better)
image

Mapping Page - Mobile - Choose Perimeter Modal Open
image

Mapping Page - Large
image

**Comment by EinEinfach** [comment]
I'll play around with your fork tomorow and if all goes well I'll merge it.

`If we keep the modals for the hidden menus, then we could better style them to better utilize the available space. Right now they are pretty nested`
- Maybe we should switch to offcanvas like the joystick panel

**Comment by rothnic** [comment]
> * Maybe we should switch to offcanvas like the joystick panel

Yeah, I agree, it is something I can play around with after this initial version. I think the scrollable offcanvas would allow us to hide away anything like that on smaller screens, and would be very consistent with the secondary column for larger screens. We'd essentially be moving the second column into the offcanvas on smaller screens. Maybe could even add another icon button in the navbar on those small screens to open it.

**Comment by EinEinfach** [comment]
Hello rothnic,

something is broken in your css styles. If I try import a sunray file the info modal message isn't large enough:

photo1694159394

Desktop mode is ok

**Comment by EinEinfach** [comment]
Also in cell phone mode I can't save new task. Modal for naming task doesn't pop up

**Comment by EinEinfach** [comment]
For a reason the new modals (e.g. perimeter select on small screens) doesn't filled with information and still empty. I can't select a perimeter in cell phone mode

**Comment by EinEinfach** [comment]
Ok, I played a little bit with mapping.py. And at least for choose perimeter we can work with callbacks. See example
`# package imports
import dash
from dash import html, dcc, Input, Output, State, callback
import dash_bootstrap_components as dbc

# local imports
from src.components import ids
from src.components.mapping import (
    map,
    uploadsunray,
    modal,
    buttons,
    buttongroupcontrol,
    chooseperimeter,
)

dash.register_page(__name__, path="/mapping", title="Mapping")


def update_layout() -> html.Div:

    # Main column, containing the map and buttons at the bottom
    main_col = dbc.Col(
        [
            html.Div(
                className="loader-wrapper flex-grow-1 p-2",
                children=[
                    dbc.Spinner(
                        delay_show=1000,
                        children=html.Div(
                            [
                                dcc.Graph(
                                    id=ids.MAPPINGMAP,
                                    figure=map.mappingmap,
                                    config={
                                        "displaylogo": False,
                                        "scrollZoom": True,
                                        #'modeBarButtonsToAdd':['eraseshape']
                                    },
                                )
                            ],
                            className="map-graph",
                        ),
                    )
                ],
                style={"overflow": "hidden"},
            ),
            dbc.Row(
                dbc.Col(
                    [
                        html.Div(
                            [
                                buttongroupcontrol.buttonhomeadd,
                                buttongroupcontrol.buttonaddnewpoint,
                                buttongroupcontrol.buttondeletelastpoint,
                                buttongroupcontrol.buttonmovepoints,
                                buttongroupcontrol.buttoncancelmapaction,
                            ],
                            className="text-center",
                        ),
                        dbc.Row(
                            [
                                dbc.Col(
                                    [
                                        buttongroupcontrol.buttonperimeteradd
                                    ],
                                    width=6,
                                    md=4,
                                    lg=3,
                                    xxl=2,
                                ),
                                dbc.Col(
                                    [
                                        buttongroupcontrol.buttonperimeterdiff
                                    ],
                                    width=6,
                                    md=4,
                                    lg=3,
                                    xxl=2,
                                ),
                            ],
                            justify="center",
                            align="center",
                            class_name="g-1 p-1"
                        ),
                        dbc.Row(
                            [
                                # column defining the width of the modal button shown on small screens
                                dbc.Col(
                                    [
                                        dbc.Button(
                                            # "Choose Perimeter",
                                            color="info",
                                            size="lg",
                                            id="open-perimeter-modal",
                                            n_clicks=0,
                                            style={"width": "100%"},
                                            class_name="bi bi-card-checklist",
                                        ),
                                        dbc.Modal(
                                            [
                                                dbc.ModalHeader(
                                                    dbc.ModalTitle("Choose Perimeter")
                                                ),
                                                dbc.ModalBody(
                                                    dbc.Col(id='modal-content-choose-perimter'),
                                                ),
                                            ],
                                            id="choose-perimeter-modal",
                                            is_open=False,
                                        ),
                                    ],
                                    width=6,
                                    md=4,
                                    lg=3,
                                    xxl=2,
                                ),
                                dbc.Col(
                                    [
                                        dbc.Button(
                                            # "Upload Sunray",
                                            id="open-sunray-modal",
                                            color="info",
                                            size="lg",
                                            class_name="bi bi-cloud-arrow-up-fill",
                                            style={"width": "100%"},
                                        ),
                                        dbc.Modal(
                                            [
                                                dbc.ModalHeader(
                                                    dbc.ModalTitle("Upload Sunray")
                                                ),
                                                dbc.ModalBody(
                                                    uploadsunray.uploadsunray
                                                ),
                                                dbc.ModalFooter(
                                                    dbc.Button(
                                                        "Close",
                                                        id="close-sunray-modal",
                                                        className="ms-auto",
                                                        n_clicks=0,
                                                    )
                                                ),
                                            ],
                                            id="upload-sunray-modal",
                                            is_open=False,
                                        ),
                                    ],
                                    width=6,
                                    md=4,
                                    lg=3,
                                    xxl=2,
                                ),
                            ],
                            justify="center",
                            align="center",
                            class_name="g-1 p-1 d-md-none d-lg-none d-xl-none d-xxl-none",
                        ),
                    ]
                ),
                style={"position": "sticky", "bottom": 0},
            ),
        ],
        class_name="flex-grow-1 d-flex flex-column",
        style={"overflow": "hidden"},
    )

    # Second column that shows the perimeter and sunray selections on larger screen sizes
    sec_col = html.Div(
        [
            dbc.Row(
                [
                    html.Div(
                        [
                            chooseperimeter.chooseperimeter,
                        ],
                        className="text-center",
                    ),
                    html.Div(
                        [
                            uploadsunray.uploadsunray,
                        ],
                        className="text-center",
                    ),
                ],
                justify="evenly",
            ),
        ],
        className="d-none d-sm-none d-md-block",
        style={"width": "330px"},
    )

    # Build the page using the two columns and remaining styles/components required
    return html.Div(
        [
            dbc.Row(
                [
                    main_col,
                    sec_col,
                    modal.sunrayimportstatus,
                    modal.overwriteperimter,
                    modal.newperimeter,
                    modal.selectperimeter,
                    modal.copyperimeter,
                    modal.removeperimeter,
                    modal.finishmapping,
                    modal.nofixsolution,
                    html.Div(id=ids.MAPPINGHIDDEN, style={"display": "none"}),
                ],
                className="flex-nowrap g-0",
                style={"height": "100%"},
            )
        ],
        style={"height": "100%", "width": "100%", "overflow": "hidden"},
    )


layout = update_layout()


# Callback to open/close perimeter selection in modal
@callback(Output("choose-perimeter-modal", "is_open"),
          Output('modal-content-choose-perimter', 'children'),
          [Input("open-perimeter-modal", "n_clicks"),
           State("choose-perimeter-modal", "is_open")
           ])
def toggle_modal(n1, is_open):
    if n1:
        return not is_open, chooseperimeter.chooseperimeter
    return is_open, chooseperimeter.chooseperimeter


# Callback to open/close sunray path upload in modal
@callback(
    Output("upload-sunray-modal", "is_open"),
    [
        Input("open-sunray-modal", "n_clicks"),
        Input("close-sunray-modal", "n_clicks"),
    ],
    [State("upload-sunray-modal", "is_open")],
)
def toggle_modal(n1, n2, is_open):
    if n1 or n2:
        return not is_open
    return is_open`

**Comment by EinEinfach** [comment]
I tried today on my iPhone. There is an issue on the bottom of the screen:
photo1694434193-changed

In the old Version it looks much better:
photo1689336086(1)

**Comment by rothnic** [comment]
>  In the old Version it looks much better:

The better spacing in the old version is only due to luck. If you instead had a phone that wasn't as tall of an aspect ratio, it was possible for the buttons to go partially off the screen and overlap that black bar even worse.

Apple can be a little bit of a pain in that they are overlapping the viewport with that black bar. On android phones it seems they do not include that bar as part of the viewport.

The app is styled to expand to the height of the viewport (available screen space), but it appears they aren't advertising the true size of the viewport. To fix this, in the updated styling, we simply need to add some additional padding on the bottom row of buttons [here](https://github.com/EinEinfach/CaSSAndRA/blob/master/CaSSAndRA/src/pages/state.py#L68). Currently there is the `p-1` helper class there that is creating the consistent padding around the buttons, but we just need to add some additional padding on the bottom to account for the black bar apple is showing there.

**Comment by rothnic** [comment]
I'd suggest trying to add `pb-2` or `pb-3` just after the `p-1` class. I'm not sure how much padding you need there, but you can try those two out.

image

**Comment by rothnic** [comment]
> pb-4 works for me, but is that the solution for everyone?

It might have to be, but let me take a quick look. I just need to update xcode so I can run an emulated iphone. I see some people mentioning this issue and there are some things I could try. What exact model is your phone?

**Comment by rothnic** [comment]
> iphone14 and iphone14pro

Which browser are you using? Or, is there a way to treat it like a web app like you can do with chrome? I seem to have trouble getting that exact view you are seeing when using safari.

image

**Comment by EinEinfach** [comment]
> > iphone14 and iphone14pro
> 
> 
> 
> Which browser are you using? Or, is there a way to treat it like a web app like you can do with chrome? I seem to have trouble getting that exact view you are seeing when using safari.
> 
> 
> 
> image
> 
> 

Yes exactly, I'm using it as a web app. Just press button with arrow an click add to homescreen.

**Comment by rothnic** [comment]
> Yes exactly, I'm using it as a web app. Just press button with arrow an click add to homescreen.

Got it, playing around with it now.

**Pull request merged**
