### PR TITLE
Responsive layout

### LINKED ISSUE #39: Responsive Layout of Interface
Hi, first of all, thanks a bunch for working on this. This is already so much better than the Sunray app and probably saved me from selling this mower. Also, I have python (web dev and data analysis with pandas), javascript (react), flutter, and web/app design experience. So, while I'll be submitting some issues in github, I also expect to pick up some of them to work on as I have time.

So, I'm using this application on a laptop, hooked up to a large monitor much of the time. The layout seems rather restricted and I'm curious if that is something that is limited by the map functionality, or just needs some basic css updates.

Here is what I see at the moment:
image

I noticed this is using bootstrap and with one quick change here:
image

From `col-lg-12 col-sm-6 col-12` to `col-lg-12 col-sm-6 col-12`, it at least takes up the full width. I wasn't able to quickly identify small changes to get it to be more "app-like" where the actions stick to the bottom and the main area expands to take up the space between the navbar and actions, but that is essentially what we probably should work towards.

image

### PR DESCRIPTION
**Pull request by rothnic**
This will add a consistent responsive layout for State and Mapping pages, plus adopts more common responsive styling for the navbar.

Closes #39 

Since there has been some additional work on the origin master branch, I'll have to integrate these changes into the latest.

### CODE REVIEW

**Comment by rothnic** [comment]
Some screenshots of the current state of this branch:

Mobile
image

Mobile with nav expanded
image

Medium size
image

Large size
image

State page larger screen, showing hidden placeholder column
image

Mapping page mobile
image

Mapping page mobile perimeter modal
image

Mapping page larger screen sizes
image

**Comment by EinEinfach** [comment]
I can take some break, and give you time to integrate your changes in current master version. Anyway it seems to have a lot of bugs in current version which will take my time.

Just let me know, should I try to resolve conflicts or just wait for new pull request.

**Comment by rothnic** [comment]
> I can take some break, and give you time to integrate your changes in current master version. Anyway it seems to have a lot of bugs in current version which will take my time.
> 
> Just let me know, should I try to resolve conflicts or just wait for new pull request.

I'll take a pass at it this afternoon (us/central). It might be a little tricky for you to merge in without some familiarity, so might be faster for me to take a pass at it. Getting the right combination of css settings was a bit tricky and likely could end up needing some tweaks after reworking it on the current master changes.

**Comment by rothnic** [comment]
This was quite a bit to integrate and I'm not sure how I was so far behind master. Closing this PR and opening a new one.

**Pull request closed without merging**
