### PR TITLE
Add dark mode

### PR DESCRIPTION
**Pull request by ShadedSelf**
There are a few things missing, mainly the plot colors, but its good enough for now.

Dbc says you need 1.5 to use dark mode, not sure if thats true though.
Ive bumped dbc and dash requirements anyways.

### CODE REVIEW

**Comment by EinEinfach** [comment]
I played a little bit with new changes. I don't know why, but I can't see selected tool in the map bar anymore. Tools working well but no idea what is currently selected

**Comment by ShadedSelf** [comment]
Should be fixed now

**Comment by EinEinfach** [comment]
What happened to the text fonts? Especially in state boxen, settings accordion...

**Comment by ShadedSelf** [comment]
What do you mean?
Its all good on my end.

**Comment by EinEinfach** [comment]
It is different to the CaSSAndRA text font style in the nav bar

**Comment by ShadedSelf** [comment]
This is how it looks for me.

Does it look different on your end?
Or should my end look differently than it does?

sdfgs

**Comment by EinEinfach** [comment]
Here is my screen shot. It looks different to your text font style
photo_5341781299007967239_y

**Comment by ShadedSelf** [comment]
Ok, that was a desktop screenshot, seems like font has a different weight on mobile with the updated minty theme, also form text and input fields seem to have different colors.

Thats just how the theme looks like now, and the previous minty theme did not support dark mode.

Do you want it changed? I can tweak a few things and make it look a bit more like the old one maybe,

**Comment by EinEinfach** [comment]
Just checked my desktop version the same issue.

But nevermind... it looks well. You don't have to spent more time to make it more familiar ;)

**Pull request merged**
