### PR TITLE
Charts styling

### PR DESCRIPTION
**Pull request by ShadedSelf**
Some styling.

I was working with an oldish branch, not sure what 97d0da4c7795a97ac10910753eae16eb3c1c570a is supposed to do, it might have been reintroduced in this PR.

### CODE REVIEW

**Comment by EinEinfach** [comment]
Looks great. Thank you.

I also work on a second pop up page with statistic data. If you want, you can also style that

**Comment by marvin78** [comment]
It would be nice, if you could click or tip on a graph and then you get a bigger version in a model or something like that. On big screens the graphs are not readable.

**Comment by ShadedSelf** [comment]
You mean font-wise?
Seems like plotly fonts only work in pixel space, so font will look small on desktop if the app is thought for mobile.
There might be a way to handle this with css, havent looked into it.

**Comment by marvin78** [comment]
It's not only the font. The charts are much too small to read anything out of them. 

For me charts are not necessary. I use influxDB and Grafana for things like that. So it would be good to have the possibility to switch them off. The additional logging could be turned off also.

**Comment by EinEinfach** [comment]
> For me charts are not necessary. I use influxDB and Grafana for things like that. So it would be good to have the possibility to switch them off. The additional logging could be turned off also.

If you don't need these features, just don't use them.

**Comment by marvin78** [comment]
That's is the point. You cannot not use them because they are there. Do the charts disappear if I change the value "Max age for measured data [days]" to 0? They do not. At least not at my installation. This is the same for the schedule. I do not use it, it is there and uses space that could be used otherwise.

**Comment by EinEinfach** [comment]
Can't follow you. Just ignore charts or schedule. It takes maybe 20% of space on your screen. Not a big deal on large screens

**Comment by marvin78** [comment]
So you can follow me. :) Space is priceless. And on mobile the menu button for the charts uses a big amount of space. 

Not a bi deal. But to my mind charts in this format a useless for everyone. If you could make them bigger by clicking on them and seing big versions of them in a modal window, it would be a good thing. And THAT was my original question. I did not want to lay focus on my needs anbd wishes.

**Comment by EinEinfach** [comment]
I added a new branch with initial statistic data. Maybe you cat take a look to that. You can style it as you want. Can you also check how stats data could be placed under the charts or over... I don't know.

**Pull request merged**
