### PR TITLE
Center mower icons

### PR DESCRIPTION
**Pull request by ShadedSelf**
Make the center of the image line up with the center of rotation.

### CODE REVIEW

**Comment by EinEinfach** [comment]
You can read my mind ;)

**Comment by EinEinfach** [comment]
thx

**Comment by EinEinfach** [comment]
But there is an issue, you have to make img symetric
Bildschirmfoto vom 2023-09-19 13-11-45

**Comment by ShadedSelf** [comment]
Oh yeah, probably need to set expand=True in the rotate() arguments

**Comment by EinEinfach** [comment]
Yeah... indeed thanks

**Comment by EinEinfach** [comment]
I'm not sure if this was the change, but I recently noticed that the size of the robot varies slightly depending on the angle. We probably need a symmetric image with width equal to height.

**Comment by ShadedSelf** [comment]
I see you pushed a symmetric image but you took it back, did it not work?

**Comment by EinEinfach** [comment]
Unfortunately it didn't. I think the image has to be cropped after rotation.

**Comment by ShadedSelf** [comment]
Did you disable expand?
If that doesnt work either I can take a look at another solution later.

**Comment by EinEinfach** [comment]
Oh... good idea, didn't try that.

**Comment by EinEinfach** [comment]
> Did you disable expand?

Thanks, seems to work

**Pull request merged**
