### PR TITLE
Add angle randomizer

### PR DESCRIPTION
**Pull request by ShadedSelf**
Adds the ability to randomize path angles in a set range.

### CODE REVIEW

**Comment by disaster123** [comment]
What’s the advantage / idea behind this?

**Comment by ShadedSelf** [comment]
If you want the rover to take a different path everytime to prevent patterns from forming.

Also, I havent tested it, but if you mow with a width way higher than your blades width and in different angles everytime, its possible that the lawn might end up looking a bit more random/natural.

**Comment by EinEinfach** [comment]
Could you create a new pull request on current version? Thx!

**Comment by ShadedSelf** [comment]
Maybe this should be redone, with tasks now it would make sense for this to be an option that changes the angle every time the  tasks is started intead of a button you press to change the angle,

**Pull request closed without merging**
